### PR TITLE
Add support for English

### PR DESCRIPTION
**Pull request by Chreer**
#14 I have followed your suggestion and add some support for English in the TUI‘s interaction area. And I will try to add support for the whole TUI.

### CODE REVIEW

**Comment by JoeanAmier** [comment]
This is a feasible code implementation, but the maintainability of the code has decreased. If more languages are supported in the future, the code submitted now will be difficult to maintain. In the near future, I will optimize the code and classify translations of all languages by object. This type of code has higher maintainability, and I look forward to your contribution.

**Comment by JoeanAmier** [comment]
There is another question. I wonder if you have tested whether the modified code can switch languages properly. It seems that the interface content has not been updated, only variables have been modified. If you are interested, you can study "textual". I am not familiar with this library yet and do not know how to update the interface.

Address: https://textual.textualize.io/

**Comment by JoeanAmier** [comment]
I have optimized the project structure. You can modify the source/translator/english.py file to add English support.

**Comment by Chreer** [comment]
Yes sir！

**Pull request closed without merging**
